### ISSUE TITLE
Wrong mask int returned for IN_ISDIR

### ISSUE THREAD

**Issue by rachelies** [arnaud-lb/php-inotify#3]
Hi,
When I read my events I don't get the right mask INT
I get 1073741825  but no such event exsits IN_ISDIR is 1073741824

**Comment by senaranya** [comment]
For someone looking for it 4 years later ... 

`1073741825` is the result of `IN_ACCESS | IN_ISDIR`, which means the event occurred is a combination of two, i.e. `IN_ACCESS` on a directory
